// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -64286847;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__schema__default_fields_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_fields",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tool = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::schema::default_fields(api_tool))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__actions__delete_files_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_files",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::types::DeleteRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::actions::delete_files(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__info__engine_info_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_info",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::info::engine_info())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__actions__export_results_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_results",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::types::ExportRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::actions::export_results(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__schema__field_defs_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "field_defs",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tool = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::schema::field_defs(api_tool))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__info__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::info::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__scan__is_scanning_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_scanning",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::scan::is_scanning())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__schema__list_tools_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_tools",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::schema::list_tools())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__scan__request_stop_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "request_stop",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::scan::request_stop())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__scan__start_scan_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_scan",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::types::ScanRequest>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<crate::api::types::ScanEvent, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::scan::start_scan(api_request, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for StreamSink<crate::api::types::ScanEvent, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::types::ColumnDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_labelKey = <String>::sse_decode(deserializer);
        let mut var_flex = <f64>::sse_decode(deserializer);
        let mut var_minWidth = <f64>::sse_decode(deserializer);
        let mut var_alignRight = <bool>::sse_decode(deserializer);
        return crate::api::types::ColumnDef {
            key: var_key,
            label_key: var_labelKey,
            flex: var_flex,
            min_width: var_minWidth,
            align_right: var_alignRight,
        };
    }
}

impl SseDecode for crate::api::types::DeleteOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_affected = <i32>::sse_decode(deserializer);
        let mut var_errors = <i32>::sse_decode(deserializer);
        let mut var_reclaimedBytes = <i64>::sse_decode(deserializer);
        let mut var_messages = <String>::sse_decode(deserializer);
        let mut var_log = <Vec<String>>::sse_decode(deserializer);
        return crate::api::types::DeleteOutcome {
            affected: var_affected,
            errors: var_errors,
            reclaimed_bytes: var_reclaimedBytes,
            messages: var_messages,
            log: var_log,
        };
    }
}

impl SseDecode for crate::api::types::DeleteRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tool = <String>::sse_decode(deserializer);
        let mut var_rows = <Vec<crate::api::types::ScanRow>>::sse_decode(deserializer);
        let mut var_deleteToTrash = <bool>::sse_decode(deserializer);
        let mut var_dryRun = <bool>::sse_decode(deserializer);
        return crate::api::types::DeleteRequest {
            tool: var_tool,
            rows: var_rows,
            delete_to_trash: var_deleteToTrash,
            dry_run: var_dryRun,
        };
    }
}

impl SseDecode for crate::api::types::EngineInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_coreVersion = <String>::sse_decode(deserializer);
        let mut var_apiVersion = <i32>::sse_decode(deserializer);
        let mut var_os = <String>::sse_decode(deserializer);
        let mut var_threadLimit = <i32>::sse_decode(deserializer);
        return crate::api::types::EngineInfo {
            core_version: var_coreVersion,
            api_version: var_apiVersion,
            os: var_os,
            thread_limit: var_threadLimit,
        };
    }
}

impl SseDecode for crate::api::types::ExportRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tool = <String>::sse_decode(deserializer);
        let mut var_rows = <Vec<crate::api::types::ScanRow>>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_format = <String>::sse_decode(deserializer);
        let mut var_grouped = <bool>::sse_decode(deserializer);
        return crate::api::types::ExportRequest {
            tool: var_tool,
            rows: var_rows,
            path: var_path,
            format: var_format,
            grouped: var_grouped,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::types::FieldDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_labelKey = <String>::sse_decode(deserializer);
        let mut var_kind = <crate::api::types::FieldKind>::sse_decode(deserializer);
        let mut var_options = <Vec<String>>::sse_decode(deserializer);
        let mut var_min = <i64>::sse_decode(deserializer);
        let mut var_max = <i64>::sse_decode(deserializer);
        return crate::api::types::FieldDef {
            id: var_id,
            label_key: var_labelKey,
            kind: var_kind,
            options: var_options,
            min: var_min,
            max: var_max,
        };
    }
}

impl SseDecode for crate::api::types::FieldKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::FieldKind::Flag,
            1 => crate::api::types::FieldKind::Choice,
            2 => crate::api::types::FieldKind::Integer,
            3 => crate::api::types::FieldKind::Text,
            4 => crate::api::types::FieldKind::TokenList,
            _ => unreachable!("Invalid variant for FieldKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::FieldPayload {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <bool>::sse_decode(deserializer);
                return crate::api::types::FieldPayload::Flag(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::types::FieldPayload::Choice(var_field0);
            }
            2 => {
                let mut var_field0 = <i64>::sse_decode(deserializer);
                return crate::api::types::FieldPayload::Integer(var_field0);
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::types::FieldPayload::Text(var_field0);
            }
            4 => {
                let mut var_field0 = <Vec<String>>::sse_decode(deserializer);
                return crate::api::types::FieldPayload::Tokens(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::FieldValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_value = <crate::api::types::FieldPayload>::sse_decode(deserializer);
        return crate::api::types::FieldValue { id: var_id, value: var_value };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::ColumnDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::ColumnDef>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::FieldDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::FieldDef>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::FieldValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::FieldValue>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<i64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::ScanRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::ScanRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::ToolSpec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::ToolSpec>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::types::ProgressUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stageLabelKey = <String>::sse_decode(deserializer);
        let mut var_current = <i64>::sse_decode(deserializer);
        let mut var_total = <i64>::sse_decode(deserializer);
        let mut var_percent = <i64>::sse_decode(deserializer);
        let mut var_detail = <String>::sse_decode(deserializer);
        return crate::api::types::ProgressUpdate {
            stage_label_key: var_stageLabelKey,
            current: var_current,
            total: var_total,
            percent: var_percent,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::types::ScanEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <crate::api::types::ProgressUpdate>::sse_decode(deserializer);
                return crate::api::types::ScanEvent::Progress(var_field0);
            }
            1 => {
                let mut var_field0 = <crate::api::types::ScanOutcome>::sse_decode(deserializer);
                return crate::api::types::ScanEvent::Completed(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::types::ScanEvent::Failed(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::ScanOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tool = <String>::sse_decode(deserializer);
        let mut var_rows = <Vec<crate::api::types::ScanRow>>::sse_decode(deserializer);
        let mut var_stopped = <bool>::sse_decode(deserializer);
        let mut var_grouped = <bool>::sse_decode(deserializer);
        let mut var_fileCount = <i32>::sse_decode(deserializer);
        let mut var_groupCount = <i32>::sse_decode(deserializer);
        let mut var_totalBytes = <i64>::sse_decode(deserializer);
        let mut var_reclaimableBytes = <i64>::sse_decode(deserializer);
        let mut var_messages = <String>::sse_decode(deserializer);
        let mut var_critical = <Option<String>>::sse_decode(deserializer);
        return crate::api::types::ScanOutcome {
            tool: var_tool,
            rows: var_rows,
            stopped: var_stopped,
            grouped: var_grouped,
            file_count: var_fileCount,
            group_count: var_groupCount,
            total_bytes: var_totalBytes,
            reclaimable_bytes: var_reclaimableBytes,
            messages: var_messages,
            critical: var_critical,
        };
    }
}

impl SseDecode for crate::api::types::ScanRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tool = <String>::sse_decode(deserializer);
        let mut var_included = <Vec<String>>::sse_decode(deserializer);
        let mut var_reference = <Vec<String>>::sse_decode(deserializer);
        let mut var_excludedPaths = <Vec<String>>::sse_decode(deserializer);
        let mut var_excludedItems = <Vec<String>>::sse_decode(deserializer);
        let mut var_allowedExtensions = <Vec<String>>::sse_decode(deserializer);
        let mut var_excludedExtensions = <Vec<String>>::sse_decode(deserializer);
        let mut var_recursive = <bool>::sse_decode(deserializer);
        let mut var_useCache = <bool>::sse_decode(deserializer);
        let mut var_minSizeKib = <String>::sse_decode(deserializer);
        let mut var_maxSizeKib = <String>::sse_decode(deserializer);
        let mut var_fields = <Vec<crate::api::types::FieldValue>>::sse_decode(deserializer);
        return crate::api::types::ScanRequest {
            tool: var_tool,
            included: var_included,
            reference: var_reference,
            excluded_paths: var_excludedPaths,
            excluded_items: var_excludedItems,
            allowed_extensions: var_allowedExtensions,
            excluded_extensions: var_excludedExtensions,
            recursive: var_recursive,
            use_cache: var_useCache,
            min_size_kib: var_minSizeKib,
            max_size_kib: var_maxSizeKib,
            fields: var_fields,
        };
    }
}

impl SseDecode for crate::api::types::ScanRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_directory = <String>::sse_decode(deserializer);
        let mut var_cells = <Vec<String>>::sse_decode(deserializer);
        let mut var_sizeBytes = <i64>::sse_decode(deserializer);
        let mut var_modifiedTs = <i64>::sse_decode(deserializer);
        let mut var_groupIndex = <i32>::sse_decode(deserializer);
        let mut var_groupSize = <i32>::sse_decode(deserializer);
        let mut var_isGroupStart = <bool>::sse_decode(deserializer);
        let mut var_isReference = <bool>::sse_decode(deserializer);
        let mut var_sortKeys = <Vec<i64>>::sse_decode(deserializer);
        return crate::api::types::ScanRow {
            path: var_path,
            name: var_name,
            directory: var_directory,
            cells: var_cells,
            size_bytes: var_sizeBytes,
            modified_ts: var_modifiedTs,
            group_index: var_groupIndex,
            group_size: var_groupSize,
            is_group_start: var_isGroupStart,
            is_reference: var_isReference,
            sort_keys: var_sortKeys,
        };
    }
}

impl SseDecode for crate::api::types::ToolSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_glyph = <String>::sse_decode(deserializer);
        let mut var_labelKey = <String>::sse_decode(deserializer);
        let mut var_grouped = <bool>::sse_decode(deserializer);
        let mut var_supportsReference = <bool>::sse_decode(deserializer);
        let mut var_columns = <Vec<crate::api::types::ColumnDef>>::sse_decode(deserializer);
        let mut var_fieldIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::types::ToolSpec {
            id: var_id,
            glyph: var_glyph,
            label_key: var_labelKey,
            grouped: var_grouped,
            supports_reference: var_supportsReference,
            columns: var_columns,
            field_ids: var_fieldIds,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__actions__delete_files_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__actions__export_results_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__info__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__scan__start_scan_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__schema__default_fields_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__info__engine_info_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__schema__field_defs_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__scan__is_scanning_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__schema__list_tools_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__scan__request_stop_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ColumnDef {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.label_key.into_into_dart().into_dart(),
            self.flex.into_into_dart().into_dart(),
            self.min_width.into_into_dart().into_dart(),
            self.align_right.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ColumnDef {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ColumnDef> for crate::api::types::ColumnDef {
    fn into_into_dart(self) -> crate::api::types::ColumnDef {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::DeleteOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.affected.into_into_dart().into_dart(),
            self.errors.into_into_dart().into_dart(),
            self.reclaimed_bytes.into_into_dart().into_dart(),
            self.messages.into_into_dart().into_dart(),
            self.log.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::DeleteOutcome {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::DeleteOutcome> for crate::api::types::DeleteOutcome {
    fn into_into_dart(self) -> crate::api::types::DeleteOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::DeleteRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tool.into_into_dart().into_dart(),
            self.rows.into_into_dart().into_dart(),
            self.delete_to_trash.into_into_dart().into_dart(),
            self.dry_run.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::DeleteRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::DeleteRequest> for crate::api::types::DeleteRequest {
    fn into_into_dart(self) -> crate::api::types::DeleteRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::EngineInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.core_version.into_into_dart().into_dart(),
            self.api_version.into_into_dart().into_dart(),
            self.os.into_into_dart().into_dart(),
            self.thread_limit.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::EngineInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::EngineInfo> for crate::api::types::EngineInfo {
    fn into_into_dart(self) -> crate::api::types::EngineInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ExportRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tool.into_into_dart().into_dart(),
            self.rows.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.grouped.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ExportRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ExportRequest> for crate::api::types::ExportRequest {
    fn into_into_dart(self) -> crate::api::types::ExportRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FieldDef {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label_key.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.options.into_into_dart().into_dart(),
            self.min.into_into_dart().into_dart(),
            self.max.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FieldDef {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FieldDef> for crate::api::types::FieldDef {
    fn into_into_dart(self) -> crate::api::types::FieldDef {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FieldKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Flag => 0.into_dart(),
            Self::Choice => 1.into_dart(),
            Self::Integer => 2.into_dart(),
            Self::Text => 3.into_dart(),
            Self::TokenList => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FieldKind {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FieldKind> for crate::api::types::FieldKind {
    fn into_into_dart(self) -> crate::api::types::FieldKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FieldPayload {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::FieldPayload::Flag(field0) => [0.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::FieldPayload::Choice(field0) => [1.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::FieldPayload::Integer(field0) => [2.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::FieldPayload::Text(field0) => [3.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::FieldPayload::Tokens(field0) => [4.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FieldPayload {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FieldPayload> for crate::api::types::FieldPayload {
    fn into_into_dart(self) -> crate::api::types::FieldPayload {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FieldValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.id.into_into_dart().into_dart(), self.value.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FieldValue {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FieldValue> for crate::api::types::FieldValue {
    fn into_into_dart(self) -> crate::api::types::FieldValue {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ProgressUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage_label_key.into_into_dart().into_dart(),
            self.current.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
            self.percent.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ProgressUpdate {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ProgressUpdate> for crate::api::types::ProgressUpdate {
    fn into_into_dart(self) -> crate::api::types::ProgressUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ScanEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::ScanEvent::Progress(field0) => [0.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::ScanEvent::Completed(field0) => [1.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            crate::api::types::ScanEvent::Failed(field0) => [2.into_dart(), field0.into_into_dart().into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ScanEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ScanEvent> for crate::api::types::ScanEvent {
    fn into_into_dart(self) -> crate::api::types::ScanEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ScanOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tool.into_into_dart().into_dart(),
            self.rows.into_into_dart().into_dart(),
            self.stopped.into_into_dart().into_dart(),
            self.grouped.into_into_dart().into_dart(),
            self.file_count.into_into_dart().into_dart(),
            self.group_count.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.reclaimable_bytes.into_into_dart().into_dart(),
            self.messages.into_into_dart().into_dart(),
            self.critical.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ScanOutcome {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ScanOutcome> for crate::api::types::ScanOutcome {
    fn into_into_dart(self) -> crate::api::types::ScanOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ScanRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tool.into_into_dart().into_dart(),
            self.included.into_into_dart().into_dart(),
            self.reference.into_into_dart().into_dart(),
            self.excluded_paths.into_into_dart().into_dart(),
            self.excluded_items.into_into_dart().into_dart(),
            self.allowed_extensions.into_into_dart().into_dart(),
            self.excluded_extensions.into_into_dart().into_dart(),
            self.recursive.into_into_dart().into_dart(),
            self.use_cache.into_into_dart().into_dart(),
            self.min_size_kib.into_into_dart().into_dart(),
            self.max_size_kib.into_into_dart().into_dart(),
            self.fields.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ScanRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ScanRequest> for crate::api::types::ScanRequest {
    fn into_into_dart(self) -> crate::api::types::ScanRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ScanRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.directory.into_into_dart().into_dart(),
            self.cells.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.modified_ts.into_into_dart().into_dart(),
            self.group_index.into_into_dart().into_dart(),
            self.group_size.into_into_dart().into_dart(),
            self.is_group_start.into_into_dart().into_dart(),
            self.is_reference.into_into_dart().into_dart(),
            self.sort_keys.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ScanRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ScanRow> for crate::api::types::ScanRow {
    fn into_into_dart(self) -> crate::api::types::ScanRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ToolSpec {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.glyph.into_into_dart().into_dart(),
            self.label_key.into_into_dart().into_dart(),
            self.grouped.into_into_dart().into_dart(),
            self.supports_reference.into_into_dart().into_dart(),
            self.columns.into_into_dart().into_dart(),
            self.field_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::ToolSpec {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ToolSpec> for crate::api::types::ToolSpec {
    fn into_into_dart(self) -> crate::api::types::ToolSpec {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for StreamSink<crate::api::types::ScanEvent, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::types::ColumnDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.label_key, serializer);
        <f64>::sse_encode(self.flex, serializer);
        <f64>::sse_encode(self.min_width, serializer);
        <bool>::sse_encode(self.align_right, serializer);
    }
}

impl SseEncode for crate::api::types::DeleteOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.affected, serializer);
        <i32>::sse_encode(self.errors, serializer);
        <i64>::sse_encode(self.reclaimed_bytes, serializer);
        <String>::sse_encode(self.messages, serializer);
        <Vec<String>>::sse_encode(self.log, serializer);
    }
}

impl SseEncode for crate::api::types::DeleteRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.tool, serializer);
        <Vec<crate::api::types::ScanRow>>::sse_encode(self.rows, serializer);
        <bool>::sse_encode(self.delete_to_trash, serializer);
        <bool>::sse_encode(self.dry_run, serializer);
    }
}

impl SseEncode for crate::api::types::EngineInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.core_version, serializer);
        <i32>::sse_encode(self.api_version, serializer);
        <String>::sse_encode(self.os, serializer);
        <i32>::sse_encode(self.thread_limit, serializer);
    }
}

impl SseEncode for crate::api::types::ExportRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.tool, serializer);
        <Vec<crate::api::types::ScanRow>>::sse_encode(self.rows, serializer);
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.format, serializer);
        <bool>::sse_encode(self.grouped, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::types::FieldDef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label_key, serializer);
        <crate::api::types::FieldKind>::sse_encode(self.kind, serializer);
        <Vec<String>>::sse_encode(self.options, serializer);
        <i64>::sse_encode(self.min, serializer);
        <i64>::sse_encode(self.max, serializer);
    }
}

impl SseEncode for crate::api::types::FieldKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::FieldKind::Flag => 0,
                crate::api::types::FieldKind::Choice => 1,
                crate::api::types::FieldKind::Integer => 2,
                crate::api::types::FieldKind::Text => 3,
                crate::api::types::FieldKind::TokenList => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::FieldPayload {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::FieldPayload::Flag(field0) => {
                <i32>::sse_encode(0, serializer);
                <bool>::sse_encode(field0, serializer);
            }
            crate::api::types::FieldPayload::Choice(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::types::FieldPayload::Integer(field0) => {
                <i32>::sse_encode(2, serializer);
                <i64>::sse_encode(field0, serializer);
            }
            crate::api::types::FieldPayload::Text(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::types::FieldPayload::Tokens(field0) => {
                <i32>::sse_encode(4, serializer);
                <Vec<String>>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::FieldValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <crate::api::types::FieldPayload>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::ColumnDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::ColumnDef>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::FieldDef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::FieldDef>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::FieldValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::FieldValue>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::ScanRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::ScanRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::ToolSpec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::ToolSpec>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::types::ProgressUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.stage_label_key, serializer);
        <i64>::sse_encode(self.current, serializer);
        <i64>::sse_encode(self.total, serializer);
        <i64>::sse_encode(self.percent, serializer);
        <String>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::types::ScanEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::ScanEvent::Progress(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::types::ProgressUpdate>::sse_encode(field0, serializer);
            }
            crate::api::types::ScanEvent::Completed(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::types::ScanOutcome>::sse_encode(field0, serializer);
            }
            crate::api::types::ScanEvent::Failed(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::ScanOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.tool, serializer);
        <Vec<crate::api::types::ScanRow>>::sse_encode(self.rows, serializer);
        <bool>::sse_encode(self.stopped, serializer);
        <bool>::sse_encode(self.grouped, serializer);
        <i32>::sse_encode(self.file_count, serializer);
        <i32>::sse_encode(self.group_count, serializer);
        <i64>::sse_encode(self.total_bytes, serializer);
        <i64>::sse_encode(self.reclaimable_bytes, serializer);
        <String>::sse_encode(self.messages, serializer);
        <Option<String>>::sse_encode(self.critical, serializer);
    }
}

impl SseEncode for crate::api::types::ScanRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.tool, serializer);
        <Vec<String>>::sse_encode(self.included, serializer);
        <Vec<String>>::sse_encode(self.reference, serializer);
        <Vec<String>>::sse_encode(self.excluded_paths, serializer);
        <Vec<String>>::sse_encode(self.excluded_items, serializer);
        <Vec<String>>::sse_encode(self.allowed_extensions, serializer);
        <Vec<String>>::sse_encode(self.excluded_extensions, serializer);
        <bool>::sse_encode(self.recursive, serializer);
        <bool>::sse_encode(self.use_cache, serializer);
        <String>::sse_encode(self.min_size_kib, serializer);
        <String>::sse_encode(self.max_size_kib, serializer);
        <Vec<crate::api::types::FieldValue>>::sse_encode(self.fields, serializer);
    }
}

impl SseEncode for crate::api::types::ScanRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.directory, serializer);
        <Vec<String>>::sse_encode(self.cells, serializer);
        <i64>::sse_encode(self.size_bytes, serializer);
        <i64>::sse_encode(self.modified_ts, serializer);
        <i32>::sse_encode(self.group_index, serializer);
        <i32>::sse_encode(self.group_size, serializer);
        <bool>::sse_encode(self.is_group_start, serializer);
        <bool>::sse_encode(self.is_reference, serializer);
        <Vec<i64>>::sse_encode(self.sort_keys, serializer);
    }
}

impl SseEncode for crate::api::types::ToolSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.glyph, serializer);
        <String>::sse_encode(self.label_key, serializer);
        <bool>::sse_encode(self.grouped, serializer);
        <bool>::sse_encode(self.supports_reference, serializer);
        <Vec<crate::api::types::ColumnDef>>::sse_encode(self.columns, serializer);
        <Vec<String>>::sse_encode(self.field_ids, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    use super::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco, wasm_bindgen};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    use super::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
