// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/actions.dart';
import 'api/info.dart';
import 'api/scan.dart';
import 'api/schema.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ScanEvent> dco_decode_StreamSink_scan_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeleteRequest dco_decode_box_autoadd_delete_request(dynamic raw);

  @protected
  ExportRequest dco_decode_box_autoadd_export_request(dynamic raw);

  @protected
  ProgressUpdate dco_decode_box_autoadd_progress_update(dynamic raw);

  @protected
  RenameRequest dco_decode_box_autoadd_rename_request(dynamic raw);

  @protected
  ScanOutcome dco_decode_box_autoadd_scan_outcome(dynamic raw);

  @protected
  ScanRequest dco_decode_box_autoadd_scan_request(dynamic raw);

  @protected
  ColumnDef dco_decode_column_def(dynamic raw);

  @protected
  DeleteOutcome dco_decode_delete_outcome(dynamic raw);

  @protected
  DeleteRequest dco_decode_delete_request(dynamic raw);

  @protected
  EngineInfo dco_decode_engine_info(dynamic raw);

  @protected
  ExportRequest dco_decode_export_request(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldDef dco_decode_field_def(dynamic raw);

  @protected
  FieldKind dco_decode_field_kind(dynamic raw);

  @protected
  FieldPayload dco_decode_field_payload(dynamic raw);

  @protected
  FieldValue dco_decode_field_value(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ColumnDef> dco_decode_list_column_def(dynamic raw);

  @protected
  List<FieldDef> dco_decode_list_field_def(dynamic raw);

  @protected
  List<FieldValue> dco_decode_list_field_value(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RenameItem> dco_decode_list_rename_item(dynamic raw);

  @protected
  List<ScanRow> dco_decode_list_scan_row(dynamic raw);

  @protected
  List<ToolSpec> dco_decode_list_tool_spec(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw);

  @protected
  RenameItem dco_decode_rename_item(dynamic raw);

  @protected
  RenameOutcome dco_decode_rename_outcome(dynamic raw);

  @protected
  RenameRequest dco_decode_rename_request(dynamic raw);

  @protected
  RenameStatus dco_decode_rename_status(dynamic raw);

  @protected
  ScanEvent dco_decode_scan_event(dynamic raw);

  @protected
  ScanOutcome dco_decode_scan_outcome(dynamic raw);

  @protected
  ScanRequest dco_decode_scan_request(dynamic raw);

  @protected
  ScanRow dco_decode_scan_row(dynamic raw);

  @protected
  ToolSpec dco_decode_tool_spec(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ScanEvent> sse_decode_StreamSink_scan_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeleteRequest sse_decode_box_autoadd_delete_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportRequest sse_decode_box_autoadd_export_request(
    SseDeserializer deserializer,
  );

  @protected
  ProgressUpdate sse_decode_box_autoadd_progress_update(
    SseDeserializer deserializer,
  );

  @protected
  RenameRequest sse_decode_box_autoadd_rename_request(
    SseDeserializer deserializer,
  );

  @protected
  ScanOutcome sse_decode_box_autoadd_scan_outcome(SseDeserializer deserializer);

  @protected
  ScanRequest sse_decode_box_autoadd_scan_request(SseDeserializer deserializer);

  @protected
  ColumnDef sse_decode_column_def(SseDeserializer deserializer);

  @protected
  DeleteOutcome sse_decode_delete_outcome(SseDeserializer deserializer);

  @protected
  DeleteRequest sse_decode_delete_request(SseDeserializer deserializer);

  @protected
  EngineInfo sse_decode_engine_info(SseDeserializer deserializer);

  @protected
  ExportRequest sse_decode_export_request(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldDef sse_decode_field_def(SseDeserializer deserializer);

  @protected
  FieldKind sse_decode_field_kind(SseDeserializer deserializer);

  @protected
  FieldPayload sse_decode_field_payload(SseDeserializer deserializer);

  @protected
  FieldValue sse_decode_field_value(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ColumnDef> sse_decode_list_column_def(SseDeserializer deserializer);

  @protected
  List<FieldDef> sse_decode_list_field_def(SseDeserializer deserializer);

  @protected
  List<FieldValue> sse_decode_list_field_value(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RenameItem> sse_decode_list_rename_item(SseDeserializer deserializer);

  @protected
  List<ScanRow> sse_decode_list_scan_row(SseDeserializer deserializer);

  @protected
  List<ToolSpec> sse_decode_list_tool_spec(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer);

  @protected
  RenameItem sse_decode_rename_item(SseDeserializer deserializer);

  @protected
  RenameOutcome sse_decode_rename_outcome(SseDeserializer deserializer);

  @protected
  RenameRequest sse_decode_rename_request(SseDeserializer deserializer);

  @protected
  RenameStatus sse_decode_rename_status(SseDeserializer deserializer);

  @protected
  ScanEvent sse_decode_scan_event(SseDeserializer deserializer);

  @protected
  ScanOutcome sse_decode_scan_outcome(SseDeserializer deserializer);

  @protected
  ScanRequest sse_decode_scan_request(SseDeserializer deserializer);

  @protected
  ScanRow sse_decode_scan_row(SseDeserializer deserializer);

  @protected
  ToolSpec sse_decode_tool_spec(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_scan_event_Sse(
    RustStreamSink<ScanEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delete_request(
    DeleteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_request(
    ExportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_progress_update(
    ProgressUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rename_request(
    RenameRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_outcome(
    ScanOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_request(
    ScanRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_column_def(ColumnDef self, SseSerializer serializer);

  @protected
  void sse_encode_delete_outcome(DeleteOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_delete_request(DeleteRequest self, SseSerializer serializer);

  @protected
  void sse_encode_engine_info(EngineInfo self, SseSerializer serializer);

  @protected
  void sse_encode_export_request(ExportRequest self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_def(FieldDef self, SseSerializer serializer);

  @protected
  void sse_encode_field_kind(FieldKind self, SseSerializer serializer);

  @protected
  void sse_encode_field_payload(FieldPayload self, SseSerializer serializer);

  @protected
  void sse_encode_field_value(FieldValue self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_column_def(
    List<ColumnDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_def(List<FieldDef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_field_value(
    List<FieldValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rename_item(
    List<RenameItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scan_row(List<ScanRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tool_spec(List<ToolSpec> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_progress_update(
    ProgressUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rename_item(RenameItem self, SseSerializer serializer);

  @protected
  void sse_encode_rename_outcome(RenameOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_rename_request(RenameRequest self, SseSerializer serializer);

  @protected
  void sse_encode_rename_status(RenameStatus self, SseSerializer serializer);

  @protected
  void sse_encode_scan_event(ScanEvent self, SseSerializer serializer);

  @protected
  void sse_encode_scan_outcome(ScanOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_scan_request(ScanRequest self, SseSerializer serializer);

  @protected
  void sse_encode_scan_row(ScanRow self, SseSerializer serializer);

  @protected
  void sse_encode_tool_spec(ToolSpec self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
