// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Deletes or trashes the selected rows through the engine's own file operations, so trash
/// behaviour matches every other frontend. Dry run plans without touching the filesystem.
Future<DeleteOutcome> deleteFiles({required DeleteRequest request}) =>
    RustLib.instance.api.crateApiActionsDeleteFiles(request: request);

/// Writes the current result set to disk as JSON or CSV.
Future<String> exportResults({required ExportRequest request}) =>
    RustLib.instance.api.crateApiActionsExportResults(request: request);
