// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Deletes or trashes the selected rows through the engine's own file operations, so trash
/// behaviour matches every other frontend. Dry run plans without touching the filesystem.
Future<DeleteOutcome> deleteFiles({required DeleteRequest request}) =>
    RustLib.instance.api.crateApiActionsDeleteFiles(request: request);

/// Writes the current result set to disk as JSON or CSV.
Future<String> exportResults({required ExportRequest request}) =>
    RustLib.instance.api.crateApiActionsExportResults(request: request);

/// Renames the selected files to the names the engine considers correct, for the two tools whose
/// result is a name: bad names and bad extensions. A dry run reports the plan without touching disk.
Future<RenameOutcome> renameFiles({required RenameRequest request}) =>
    RustLib.instance.api.crateApiActionsRenameFiles(request: request);

/// Moves or copies the selection into a destination folder. czkawka_core has no move API, so this is
/// the one action the frontend owns outright. A dry run plans it, and a name already in the
/// destination is skipped unless the request asks for something else.
Future<MoveOutcome> moveFiles({required MoveRequest request}) =>
    RustLib.instance.api.crateApiActionsMoveFiles(request: request);

/// Strips EXIF tags from the selected photos through the engine's own remover. The original file is
/// left alone by default and the cleaned copy is written beside it; `override_file` replaces it.
Future<ExifOutcome> cleanExif({required ExifRequest request}) =>
    RustLib.instance.api.crateApiActionsCleanExif(request: request);

/// Sorts files into the set folders the board chose for a similar-images result. Nothing is ever
/// written over an existing file, and each scanned root gets an undo journal that `undo_simiu_set`
/// can replay. A dry run reports the plan and writes no journal.
Future<SimiuApplyOutcome> applySimiuSet({required SimiuApplyRequest request}) =>
    RustLib.instance.api.crateApiActionsApplySimiuSet(request: request);

/// Reverses one Simiu undo journal, newest operation first. Copy and link results are removed again;
/// a move goes back to its recorded source unless something else took that name.
Future<SimiuUndoOutcome> undoSimiuSet({required SimiuUndoRequest request}) =>
    RustLib.instance.api.crateApiActionsUndoSimiuSet(request: request);
