// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Flex, minimum width and right alignment for one column key, or the neutral defaults when a new
/// column has not been given a layout yet.
Future<(double, double, bool)> layout({required String key}) =>
    RustLib.instance.api.crateApiPresentationLayout(key: key);
