// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Starts a scan and streams every engine progress tick, ending with exactly one terminal event.
Stream<ScanEvent> startScan({required ScanRequest request}) =>
    RustLib.instance.api.crateApiScanStartScan(request: request);

/// Asks whatever is in flight to stop at its next checkpoint: a scan keeps its partial result, and a
/// file operation reports the rows it never attempted as stopped. Returns false when nothing runs.
bool requestStop() => RustLib.instance.api.crateApiScanRequestStop();

/// Whether a scan is running. File operations are not scans: they are serialized on their own stop
/// flag, so a second one is refused rather than started.
bool isScanning() => RustLib.instance.api.crateApiScanIsScanning();
