// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Starts a scan and streams every engine progress tick, ending with exactly one terminal event.
Stream<ScanEvent> startScan({required ScanRequest request}) =>
    RustLib.instance.api.crateApiScanStartScan(request: request);

/// Asks the running scan to stop at the next checkpoint; the partial result is still delivered.
bool requestStop() => RustLib.instance.api.crateApiScanRequestStop();

bool isScanning() => RustLib.instance.api.crateApiScanIsScanning();
