// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// All scanners, in the order the tool menu and results table expect.
List<ToolSpec> listTools() => RustLib.instance.api.crateApiSchemaListTools();

List<FieldDef> fieldDefs({required String tool}) =>
    RustLib.instance.api.crateApiSchemaFieldDefs(tool: tool);

List<FieldValue> defaultFields({required String tool}) =>
    RustLib.instance.api.crateApiSchemaDefaultFields(tool: tool);
