// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class ColumnDef {
  final String key;
  final String labelKey;
  final double flex;
  final double minWidth;
  final bool alignRight;

  const ColumnDef({
    required this.key,
    required this.labelKey,
    required this.flex,
    required this.minWidth,
    required this.alignRight,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      labelKey.hashCode ^
      flex.hashCode ^
      minWidth.hashCode ^
      alignRight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnDef &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          labelKey == other.labelKey &&
          flex == other.flex &&
          minWidth == other.minWidth &&
          alignRight == other.alignRight;
}

/// What to do when the destination already holds the requested name. `Skip` is the default because
/// a GUI action must never destroy a file the user did not choose to replace.
enum ConflictPolicy {
  skip,
  overwrite,

  /// Takes `name (1).ext`, `name (2).ext`, ... until a slot is free.
  rename,
  error,
}

class DeleteOutcome {
  final int affected;
  final int errors;
  final PlatformInt64 reclaimedBytes;
  final String messages;
  final List<String> log;

  const DeleteOutcome({
    required this.affected,
    required this.errors,
    required this.reclaimedBytes,
    required this.messages,
    required this.log,
  });

  @override
  int get hashCode =>
      affected.hashCode ^
      errors.hashCode ^
      reclaimedBytes.hashCode ^
      messages.hashCode ^
      log.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteOutcome &&
          runtimeType == other.runtimeType &&
          affected == other.affected &&
          errors == other.errors &&
          reclaimedBytes == other.reclaimedBytes &&
          messages == other.messages &&
          log == other.log;
}

class DeleteRequest {
  final String tool;
  final List<ScanRow> rows;
  final bool deleteToTrash;
  final bool dryRun;

  const DeleteRequest({
    required this.tool,
    required this.rows,
    required this.deleteToTrash,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      tool.hashCode ^ rows.hashCode ^ deleteToTrash.hashCode ^ dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteRequest &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          rows == other.rows &&
          deleteToTrash == other.deleteToTrash &&
          dryRun == other.dryRun;
}

class EngineInfo {
  final String coreVersion;
  final int apiVersion;
  final String os;
  final int threadLimit;

  const EngineInfo({
    required this.coreVersion,
    required this.apiVersion,
    required this.os,
    required this.threadLimit,
  });

  @override
  int get hashCode =>
      coreVersion.hashCode ^
      apiVersion.hashCode ^
      os.hashCode ^
      threadLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInfo &&
          runtimeType == other.runtimeType &&
          coreVersion == other.coreVersion &&
          apiVersion == other.apiVersion &&
          os == other.os &&
          threadLimit == other.threadLimit;
}

class ExportRequest {
  final String tool;
  final List<ScanRow> rows;
  final String path;
  final String format;
  final bool grouped;

  const ExportRequest({
    required this.tool,
    required this.rows,
    required this.path,
    required this.format,
    required this.grouped,
  });

  @override
  int get hashCode =>
      tool.hashCode ^
      rows.hashCode ^
      path.hashCode ^
      format.hashCode ^
      grouped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportRequest &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          rows == other.rows &&
          path == other.path &&
          format == other.format &&
          grouped == other.grouped;
}

class FieldDef {
  final String id;
  final String labelKey;
  final FieldKind kind;
  final List<String> options;
  final PlatformInt64 min;
  final PlatformInt64 max;

  const FieldDef({
    required this.id,
    required this.labelKey,
    required this.kind,
    required this.options,
    required this.min,
    required this.max,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      labelKey.hashCode ^
      kind.hashCode ^
      options.hashCode ^
      min.hashCode ^
      max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDef &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          labelKey == other.labelKey &&
          kind == other.kind &&
          options == other.options &&
          min == other.min &&
          max == other.max;
}

/// How Dart should render one option of the algorithm tab.
enum FieldKind { flag, choice, integer, text, tokenList }

@freezed
sealed class FieldPayload with _$FieldPayload {
  const FieldPayload._();

  const factory FieldPayload.flag(bool field0) = FieldPayload_Flag;
  const factory FieldPayload.choice(String field0) = FieldPayload_Choice;
  const factory FieldPayload.integer(PlatformInt64 field0) =
      FieldPayload_Integer;
  const factory FieldPayload.text(String field0) = FieldPayload_Text;
  const factory FieldPayload.tokens(List<String> field0) = FieldPayload_Tokens;
}

class FieldValue {
  final String id;
  final FieldPayload value;

  const FieldValue({required this.id, required this.value});

  @override
  int get hashCode => id.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldValue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value;
}

/// Whether the original stays where it is.
enum MoveAction { move, copy }

class MoveItem {
  final String from;
  final String to;
  final MoveStatus status;
  final String detail;

  const MoveItem({
    required this.from,
    required this.to,
    required this.status,
    required this.detail,
  });

  @override
  int get hashCode =>
      from.hashCode ^ to.hashCode ^ status.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveItem &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          status == other.status &&
          detail == other.detail;
}

class MoveOutcome {
  final int moved;
  final int copied;
  final int planned;
  final int skipped;
  final int failed;

  /// One entry per selected path, in request order.
  final List<MoveItem> items;
  final String messages;

  const MoveOutcome({
    required this.moved,
    required this.copied,
    required this.planned,
    required this.skipped,
    required this.failed,
    required this.items,
    required this.messages,
  });

  @override
  int get hashCode =>
      moved.hashCode ^
      copied.hashCode ^
      planned.hashCode ^
      skipped.hashCode ^
      failed.hashCode ^
      items.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveOutcome &&
          runtimeType == other.runtimeType &&
          moved == other.moved &&
          copied == other.copied &&
          planned == other.planned &&
          skipped == other.skipped &&
          failed == other.failed &&
          items == other.items &&
          messages == other.messages;
}

/// Moves or copies the selection into one destination folder.
class MoveRequest {
  final List<String> paths;
  final String destination;
  final MoveAction action;
  final ConflictPolicy conflict;

  /// Mirrors each file's folder trail under the filesystem root instead of dropping everything
  /// into the destination flat.
  final bool preserveStructure;
  final bool dryRun;

  const MoveRequest({
    required this.paths,
    required this.destination,
    required this.action,
    required this.conflict,
    required this.preserveStructure,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      paths.hashCode ^
      destination.hashCode ^
      action.hashCode ^
      conflict.hashCode ^
      preserveStructure.hashCode ^
      dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveRequest &&
          runtimeType == other.runtimeType &&
          paths == other.paths &&
          destination == other.destination &&
          action == other.action &&
          conflict == other.conflict &&
          preserveStructure == other.preserveStructure &&
          dryRun == other.dryRun;
}

/// What happened to one selected file.
enum MoveStatus { moved, copied, planned, skipped, failed }

class ProgressUpdate {
  final String stageLabelKey;
  final PlatformInt64 current;
  final PlatformInt64 total;
  final PlatformInt64 percent;
  final String detail;

  const ProgressUpdate({
    required this.stageLabelKey,
    required this.current,
    required this.total,
    required this.percent,
    required this.detail,
  });

  @override
  int get hashCode =>
      stageLabelKey.hashCode ^
      current.hashCode ^
      total.hashCode ^
      percent.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressUpdate &&
          runtimeType == other.runtimeType &&
          stageLabelKey == other.stageLabelKey &&
          current == other.current &&
          total == other.total &&
          percent == other.percent &&
          detail == other.detail;
}

class RenameItem {
  final String from;
  final String to;
  final RenameStatus status;
  final String detail;

  const RenameItem({
    required this.from,
    required this.to,
    required this.status,
    required this.detail,
  });

  @override
  int get hashCode =>
      from.hashCode ^ to.hashCode ^ status.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameItem &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          status == other.status &&
          detail == other.detail;
}

class RenameOutcome {
  final int renamed;
  final int planned;
  final int failed;
  final int skipped;

  /// One entry per selected path, in request order.
  final List<RenameItem> items;
  final String messages;

  const RenameOutcome({
    required this.renamed,
    required this.planned,
    required this.failed,
    required this.skipped,
    required this.items,
    required this.messages,
  });

  @override
  int get hashCode =>
      renamed.hashCode ^
      planned.hashCode ^
      failed.hashCode ^
      skipped.hashCode ^
      items.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameOutcome &&
          runtimeType == other.runtimeType &&
          renamed == other.renamed &&
          planned == other.planned &&
          failed == other.failed &&
          skipped == other.skipped &&
          items == other.items &&
          messages == other.messages;
}

/// A rename run. The engine decides the new name, so the request carries the option block of the
/// scan that produced the rows plus the selection to act on. Dry run decides without touching disk.
class RenameRequest {
  final String tool;
  final ScanRequest scan;
  final List<String> paths;
  final bool dryRun;

  const RenameRequest({
    required this.tool,
    required this.scan,
    required this.paths,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      tool.hashCode ^ scan.hashCode ^ paths.hashCode ^ dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameRequest &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          scan == other.scan &&
          paths == other.paths &&
          dryRun == other.dryRun;
}

/// What happened to one selected file.
enum RenameStatus {
  /// A rename the run performed.
  renamed,

  /// A rename a dry run would have performed.
  planned,

  /// Blocked: the name was already taken or the filesystem refused.
  failed,

  /// The engine found nothing to change.
  skipped,
}

@freezed
sealed class ScanEvent with _$ScanEvent {
  const ScanEvent._();

  const factory ScanEvent.progress(ProgressUpdate field0) = ScanEvent_Progress;
  const factory ScanEvent.completed(ScanOutcome field0) = ScanEvent_Completed;
  const factory ScanEvent.failed(String field0) = ScanEvent_Failed;
}

class ScanOutcome {
  final String tool;
  final List<ScanRow> rows;
  final bool stopped;
  final bool grouped;
  final int fileCount;
  final int groupCount;
  final PlatformInt64 totalBytes;
  final PlatformInt64 reclaimableBytes;
  final String messages;
  final String? critical;

  const ScanOutcome({
    required this.tool,
    required this.rows,
    required this.stopped,
    required this.grouped,
    required this.fileCount,
    required this.groupCount,
    required this.totalBytes,
    required this.reclaimableBytes,
    required this.messages,
    this.critical,
  });

  @override
  int get hashCode =>
      tool.hashCode ^
      rows.hashCode ^
      stopped.hashCode ^
      grouped.hashCode ^
      fileCount.hashCode ^
      groupCount.hashCode ^
      totalBytes.hashCode ^
      reclaimableBytes.hashCode ^
      messages.hashCode ^
      critical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanOutcome &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          rows == other.rows &&
          stopped == other.stopped &&
          grouped == other.grouped &&
          fileCount == other.fileCount &&
          groupCount == other.groupCount &&
          totalBytes == other.totalBytes &&
          reclaimableBytes == other.reclaimableBytes &&
          messages == other.messages &&
          critical == other.critical;
}

/// Everything a single scan needs: the shared path/filter block plus the per-tool options.
class ScanRequest {
  final String tool;
  final List<String> included;
  final List<String> reference;
  final List<String> excludedPaths;
  final List<String> excludedItems;
  final List<String> allowedExtensions;
  final List<String> excludedExtensions;
  final bool recursive;
  final bool useCache;
  final String minSizeKib;
  final String maxSizeKib;
  final List<FieldValue> fields;

  const ScanRequest({
    required this.tool,
    required this.included,
    required this.reference,
    required this.excludedPaths,
    required this.excludedItems,
    required this.allowedExtensions,
    required this.excludedExtensions,
    required this.recursive,
    required this.useCache,
    required this.minSizeKib,
    required this.maxSizeKib,
    required this.fields,
  });

  @override
  int get hashCode =>
      tool.hashCode ^
      included.hashCode ^
      reference.hashCode ^
      excludedPaths.hashCode ^
      excludedItems.hashCode ^
      allowedExtensions.hashCode ^
      excludedExtensions.hashCode ^
      recursive.hashCode ^
      useCache.hashCode ^
      minSizeKib.hashCode ^
      maxSizeKib.hashCode ^
      fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRequest &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          included == other.included &&
          reference == other.reference &&
          excludedPaths == other.excludedPaths &&
          excludedItems == other.excludedItems &&
          allowedExtensions == other.allowedExtensions &&
          excludedExtensions == other.excludedExtensions &&
          recursive == other.recursive &&
          useCache == other.useCache &&
          minSizeKib == other.minSizeKib &&
          maxSizeKib == other.maxSizeKib &&
          fields == other.fields;
}

class ScanRow {
  final String path;
  final String name;
  final String directory;

  /// Extra cells aligned with `ToolSpec.columns`, already formatted for display.
  final List<String> cells;
  final PlatformInt64 sizeBytes;
  final PlatformInt64 modifiedTs;
  final int groupIndex;
  final int groupSize;
  final bool isGroupStart;
  final bool isReference;

  /// Numeric sort keys aligned with `cells`, so Dart sorts without parsing display text.
  final Int64List sortKeys;

  const ScanRow({
    required this.path,
    required this.name,
    required this.directory,
    required this.cells,
    required this.sizeBytes,
    required this.modifiedTs,
    required this.groupIndex,
    required this.groupSize,
    required this.isGroupStart,
    required this.isReference,
    required this.sortKeys,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      directory.hashCode ^
      cells.hashCode ^
      sizeBytes.hashCode ^
      modifiedTs.hashCode ^
      groupIndex.hashCode ^
      groupSize.hashCode ^
      isGroupStart.hashCode ^
      isReference.hashCode ^
      sortKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRow &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          directory == other.directory &&
          cells == other.cells &&
          sizeBytes == other.sizeBytes &&
          modifiedTs == other.modifiedTs &&
          groupIndex == other.groupIndex &&
          groupSize == other.groupSize &&
          isGroupStart == other.isGroupStart &&
          isReference == other.isReference &&
          sortKeys == other.sortKeys;
}

/// One user-facing scanner, described so Dart can render it without hardcoding a table per tool.
class ToolSpec {
  final String id;
  final String glyph;
  final String labelKey;
  final bool grouped;
  final bool supportsReference;
  final List<ColumnDef> columns;
  final List<String> fieldIds;

  const ToolSpec({
    required this.id,
    required this.glyph,
    required this.labelKey,
    required this.grouped,
    required this.supportsReference,
    required this.columns,
    required this.fieldIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      glyph.hashCode ^
      labelKey.hashCode ^
      grouped.hashCode ^
      supportsReference.hashCode ^
      columns.hashCode ^
      fieldIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolSpec &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          glyph == other.glyph &&
          labelKey == other.labelKey &&
          grouped == other.grouped &&
          supportsReference == other.supportsReference &&
          columns == other.columns &&
          fieldIds == other.fieldIds;
}
